-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 03 Haz 2025, 19:32:47
-- Sunucu sürümü: 10.4.32-MariaDB
-- PHP Sürümü: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `faqs_db`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `sss`
--

CREATE TABLE `sss` (
  `id` int(11) NOT NULL,
  `question` text DEFAULT NULL,
  `answer` text DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

--
-- Tablo döküm verisi `sss`
--

INSERT INTO `sss` (`id`, `question`, `answer`, `category`) VALUES
(1, 'Yüksek lisans ve doktora programlarına başvurular ne zaman yapılmaktadır?', 'Lisansüstü programlara başvurular güz ve bahar yarıyılları başlamadan önce yapılmaktadır.  Lisansüstü programlara başvurular Üniversitemiz ve Enstitümüz sayfasından paylaşılmaktadır. Ayrıca ilanlar, sosyal medya hesaplarımızdan da paylaşılmaktadır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(2, 'Yüksek lisans ve doktora programlarına başvurular nasıl yapılmaktadır?', 'Yüksek lisans ve doktora programlarına başvurular enstitubasvuru.firat.edu.tr adresi üzerinden çevrim içi olarak yapılmaktadır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(3, 'Aynı anda birden fazla lisansüstü programa başvuru yapabilir miyim?', 'Herhangi bir tezli lisansüstü programına müracaat eden aday, aynı anda başka bir anabilim dalı/programa veya başka bir enstitüde tezli yüksek lisans programına müracaat edemezler. Birden fazla başvuru olması hâlinde adayın tüm başvuruları geçersiz sayılır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(4, 'Lisansüstü programlara başvurularda ALES puanı kaç olmalıdır?', 'Lisansüstü programlara müracaatlarda, başvurulan programın puan türünde standart ALES puanının en az 55 olma şartı aranır. Değerlendirmede Üniversitemiz Senatosu tarafından belirlenmiş ALES puanı esas alınır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(5, 'Doktora programlarına başvuruda yabancı dil puanı kaç olmalıdır?', 'Doktora programlarına başvuru için ilgili alandaki yabancı dil sınav notunun en az 55 olması gerekir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(6, 'Tezsiz yüksek lisans programlarına öğrenci kabulü nasıl yapılır?', 'Tezsiz yüksek lisans programlarına öğrenci kabulünde, adayın YÖKSİS’te kayıtlı lisans mezuniyet notu dikkate alınır. Mezuniyet notu en yüksek olandan başlamak üzere adaylar sıralamaya tabi tutulur.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(7, 'Tezsiz yüksek lisans programından mezun olan adaylar doktora programına başvurabilirler mi?', 'Tezsiz yüksek lisans diploması ile doktora programına başvuru yapılamaz.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(8, 'Doktora programlarına başvuru için mezuniyet ortalaması kaç olmalıdır?', 'Doktora Programlarına başvuru için mezuniyet not ortalaması, Yabancı dil hazırlık sınıfı hariç en az 10 (on) yarıyıl süreli lisans diplomasına sahip olan adaylarda 65/100 şartı aranır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(9, 'Lisans derecesiyle doktora programına başvuru yapan adayların mezuniyet notları, ALES puanları ve yabancı dil puanları kaç olmalıdır?', 'Lisans derecesiyle (hazırlık sınıfı hariç dört yıllık lisans diploması) doktora programına başvuran adayların lisans mezuniyet not ortalamalarının 4 üzerinden en az 3 veya muadili bir puana, 80 ALES puanına ve yabancı dil sınavından (YDS, YÖKDİL, e-YDS veya eşdeğer sınavlardan) 55 puana sahip olması gerekir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(10, 'Lisansüstü programlara başvurularda başarı puanı hesaplanırken mezuniyet notu nasıl hesaplanır?', 'Başarı puanının hesaplanmasında adayın YÖKSİS’te kayıtlı mezuniyet notu esas alınır. Mezuniyet notu YÖKSİS’te 4’lük ise YÖK’ün dönüşüm tablosuna göre 100’lük sisteme dönüştürülür. YÖKSİS’te 100’lük mezuniyet notu varsa bu not kullanılır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(11, 'Farklı Alan Sınavı (FAS) nedir?', 'Başvuracağı yüksek lisans programından farklı alandan mezun olan adaylar, öncelikle başvurduğu alanla ilgili yazılı olarak girmiş oldukları sınav, Farklı Alan Sınavıdır (FAS).', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(12, 'Farklı Alana Sınavından başarılı olmak için kaç puan almak gerekir?', 'Farklı Alan Sınavından başarılı olmak için sınav puanının 50/100 ve üzeri olması gerekir. Bu sınavdan 50/100 veya üzerinde puan alan adaylar, genel değerlendirmeye alınır. Puanı 50/100’den düşük olan veya sınava girmeyen adaylar başarısız kabul edilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(13, 'Yüksek lisans başvuruları nasıl değerlendirilmektedir?', 'Yüksek lisans için başvuruların değerlendirmesi: ALES puanı x 0.5 + lisans mezuniyet notu x 0.4 + (varsa yabancı dil puanı x 0.1) şeklinde hesaplanan başarı puanları 50 ve üzerinde olan adaylar, puanına göre sıralamaya tabi tutulur. Yabancı dil puanının hesaplamaya dâhil edilebilmesi için en az 40 olması gerekir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(14, 'Yüksek lisans başvurularında yabancı dil puanı şart mıdır?', 'Hayır, şart değildir. Ancak yüksek lisans başvurularında yabancı dil puanının hesaplamaya dahil edilebilmesi için yabancı dil puanının en az 40 puan olması gerekmektedir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(15, 'Lisans derecesi ile doktora programına başvurularda başvuru puanı nasıl hesaplanır?', 'Lisans derecesi ile doktora için başvuruların değerlendirmesi: ALES puanı x 0.5 + lisans mezuniyet notu x 0.2 + yabancı dil puanı x 0.2 + bilimsel değerlendirme sınav notu x 0.1 şeklinde hesaplanmaktadır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(16, 'Lisans derecesi ile doktora programına başvurularda sıralamaya girebilmek için başvuru puanı en az kaç olmalıdır?', 'Başarı puanları 65 ve üzerinde olan adaylar, puanlarına göre sıralamaya tabi tutulurlar.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(17, 'Yüksek lisans derecesi ile doktora için başvuruların değerlendirmesi nasıl yapılır?', 'ALES puanı x 0.5 + yüksek lisans mezuniyet notu x 0.2 + yabancı dil puanı x 0.2 + bilimsel değerlendirme sınav notu x 0.1 şeklinde hesaplanan başarı puanları 65 ve üzerinde olan adaylar, puanlarına göre sıralamaya tabi tutulur. Doktora için ilan edilen kontenjan kadar, lisans/yüksek lisans derecesi ile müracaat eden adayların tamamından, asıl ve iki katı kadar yedek aday listeleri belirlenir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(18, 'Doktora programına başvurularda başarı puanları eşit olan adaylar arasında seçim nasıl yapılır?', 'Eşitlik hâlinde ALES notu yüksek olan adaya öncelik verilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(19, 'Doktora programlarına başvurularda bilimsel değerlendirme sınavından (BDS) kaç almak gerekir?', 'Doktora için başvurularda, başvurduğu anabilim dalında yapılacak BDS’de 50/100 ve üzerinde puan alan aday değerlendirmeye alınır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(20, 'Bilimsel değerlendirme sınavı (BDS) hangi bölümlerden oluşur? Katkı oranları nedir?', 'BDS yazılı ve sözlü olarak iki bölüm halinde yapılır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(21, 'Bilimsel değerlendirme sınavında (BDS)  yazılı ve sözlü sınav notlarının katkı oranları nedir?', 'Yazılı sınav notunun % 65’i ile sözlü sınav notunun % 35’inin toplamı sınav puanı olarak alınır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(22, 'Bilimsel değerlendirme sınavının (BDS) başarılı olmak için kaç puan almak gereklidir?', 'Sınavda başarılı olmak için sınav puanının 50/100 ve üzeri olması gerekir. Puanı 50/100’den düşük olan veya sınavlardan birine girmeyen adaylar başarısız kabul edilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(23, 'Kazanan adaylar kesin kayıt işlemlerini nasıl yapmaktadırlar?', 'Başvuru süreci sonunda lisansüstü programlara yerleşen adaylar kesin kayıt işlemlerini enstitübasvuru.firat.edu.tr sistemi üzerinden sisteme girip belgelerine onay vererek yapmaktadırlar.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(24, 'Kazanan adaylar danışman seçimini nasıl ve ne zaman yapmaktadırlar?', 'Lisansüstü programlara yerleşen adayların enstitübasvuru.firat.edu.tr sistemi üzerinden  yapmış oldukları kesin kayıt süreci ile birlikte danışman tercihlerini de yapmaktadırlar.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(25, 'Danışman tercihim ne zaman onaylanır?', 'Lisansüstü programları kazanan adayların danışman tercihlerinden sonra Ana Bilim Dalı Kurul kararı ve Enstitü Yönetim Kurulu kararı ile danışmanları kesinlik kazanır. Danışman belirlenmesi yönetmelik/yönergelere göre en geç birinci dönemin sonuna kadar yapılır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(26, 'Kesin kayıt hakkı kazanana kayıt takvimi içerisinde kayıt yaptırmazsa hak iddia edebilir mi?', 'Hayır. İlan edilen kesin kayıt takvimi içinde kayıt yaptırmayan adaylar kayıt hakkını kaybeder.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(27, 'Lisansüstü programlara yapılan başvurulardaki sınav sonuçlarına ve sıralamalara itiraz edilebilir mi?', 'Adaylar, değerlendirme sonuçları açıklandıktan sonra 3 iş günü içerisinde ilgili enstitüye itiraz edebilir. Sınav evrakları, sınav jürisi tarafından maddi açıdan incelenerek sonuç enstitü aracılığı ile adaya bildirilir. ÖZEL ÖĞRENCİ, YATAY GEÇİŞLER, VE BİLİMSEL HAZIRLIK', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(28, 'Özel öğrenci kabul şartları nelerdir?', 'Bir lisansüstü programa kayıtlı olan öğrenci, diğer yükseköğretim kurumlarındaki lisansüstü derslere, kayıtlı olduğu enstitü anabilim/anasanat dalı başkanlığının onayı ile özel öğrenci olarak kabul edilebilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(29, 'Özel öğrenci olarak kabul edilen öğrenci en fazla kaç ders alabilir?', 'Lisansüstü derslere kabul edilen öğrencilerin özel öğrenci olarak aldığı ve başarılı olduğu en fazla iki dersin muafiyet işlemleri kayıtlı olduğu enstitü anabilim/anasanat dalı başkanlığı tarafından yürütülür.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(30, 'Yatay geçiş yoluyla öğrenci kabul şartları nelerdir?', 'Yükseköğretim kurumu içindeki başka bir enstitü anabilim/anasanat dalında veya başka bir yükseköğretim kurumunun lisansüstü programında en az bir yarıyılı tamamlamış olan başarılı öğrenci, lisansüstü programlara yatay geçiş yoluyla kabul edilebilir. Programların eş değer olup olmadığına, geçiş yapılmak istenen EABD Kurulu/Program Yürütme Kurulu ve enstitü yönetim kurulu tarafından, her iki programın müfredat dersleri ile tez konularının en az %60 oranında yakınlığı gerekçe gösterilerek karar verilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(31, 'Yatay geçiş için başvuru yapan öğrencinin başvuru kaç olmalıdır?', 'Yatay geçiş için başvuran öğrencinin, başvuru yapacağı programa en son kabul edilen öğrencinin başvuru puanına eşit veya daha yüksek bir puana sahip olması gerekir. Yatay geçiş başvurusunda güncel sınav belgeleri kullanılabilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(32, 'Yatay geçiş başvurusu yapan öğrencinin başvuru puanı nasıl hesaplanır?', 'Başvuru puanı hesaplaması Üniversite tarafından ilan edilen güncel puanlamaya göre ilgili enstitü tarafından yapılır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(33, 'Doktora programına başvurularda  Bilimsel Değerlendirme Puanı kaç olarak hesaplanır?', 'Doktora programları için Bilimsel Değerlendirme Sınav puanı yüz tam puan kabul edilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(34, 'Yatay geçiş başvuruları nasıl yapılır?', 'Yatay geçiş başvuruları ilgili enstitünün yatay geçiş başvuru formu kullanılarak ve formun ek belgeleriyle birlikte ilgili enstitüye şahsen veya ilgili enstitünün kurumsal e-posta adresine yapılır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(35, 'Yatay geçiş için başvuru yapan öğrenci hangi evrakları sunmak zorundadır?', 'Yatay geçiş için enstitüye başvuran öğrenci, kayıtlı bulunduğu programda aldığı dersleri ve başarı durumunu, kayıt tarihini ve disiplin durumunu gösteren bir belgeyi sunmak zorundadır. Enstitü yönetim kurulu öğrenciden başvuru için başka belgeler de isteyebilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(36, 'Yatay geçiş için hangi öğrencilerin başvurusu kabul edilir?', 'Lisansüstü programın başvuru koşullarını ve lisansüstü yönergesinde belirtilen diğer koşulları sağlayan, normal öğrenim süresi içinde bulunan, en az bir dönem lisansüstü programda ders almış olan ve aldığı derslerin hepsinden başarılı olan öğrencilerin başvurusu kabul edilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(37, 'Tez döneminde yatay geçiş yapılır mı?', 'Evet. Tez döneminde geçiş yapanlar yeni bir tez konusu önerisi vermek zorundadır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(38, 'Yatay geçiş dışında yapılacak intibaklarda ders muafiyeti için şartlar nelerdir?', 'Bir diploma için kullanılmamış olmak koşuluyla bir öğrencinin; enstitüye kaydolmadan önceki lisansüstü programlardan alıp başardığı dersler, enstitünün ders başarı ölçütlerini sağlaması şartıyla danışmanı ve program yürütme kurulu/anabilim dalı kurulunun teklifi ve enstitü yönetim kurulunun kararıyla kayıtlı olduğu programa kredi ve başarı notuyla birlikte  F.Ü.Lisansüstü Yönergesinin  15. Maddesinin bendinde tanımlanan süreler içerisinde aktarılabilir veya muaf tutulabilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(39, 'Bilimsel Hazırlık Programı hangi öğrencilere uygulanır?', 'Yüksek lisans ve doktora programlarına kabul edilen öğrencilerden lisans veya yüksek lisans derecesini kabul edildikleri yüksek lisans veya doktora programından farklı alanlarda almış olan öğrenciler için, program yürütme kurulu/anabilim dalı kurulunun teklifi ve EYK kararıyla bilimsel hazırlık programı uygulanabilir. Bilimsel hazırlık programı uygulanmayacak öğrenciler, EABD kurulu/Program yürütme kurulunun gerekçeli kararı ile enstitüye bildirilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(40, 'Bilimsel hazırlık programında geçirilecek süre en fazla kaç yarıyıldır?', 'Bilimsel hazırlık programında geçirilecek süre en çok iki yarıyıldır. Yaz öğretiminde ders alınamaz.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(41, 'Bilimsel hazırlık programından başarısız olunması halinde süreç nasıl işler?', 'Bu süre, dönem izinleri dışında uzatılamaz ve süre sonunda başarılı olamayan öğrencinin ilişiği kesilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(42, 'Bilimsel hazırlık programında alınacak dersler nasıl belirlenir?', 'Bilimsel hazırlık programında alınacak dersler ve toplam AKTS kredi miktarı, program yürütme kurulu/ilgili anabilim dalı kurulunun önerisi ve EYK kararı ile belirlenir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(43, 'Bilimsel hazırlık programında alınacak dersler en az kaç AKTS olmalıdır?', 'Bilimsel hazırlık programında alınacak dersler en az 18 AKTS kredisinde olmalıdır.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(44, 'Bilimsel hazırlık programında bir yarıyılda en çok kaç AKTS alınır?', 'Bilimsel hazırlık programında bir öğrenci bir yarıyılda en çok 20 AKTS kredisinde ders alabilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(45, 'Bilimsel hazırlık programında alınması gereken zorunlu derslerin seçimi nasıl olur?', 'Bilimsel hazırlık programında alınması gereken zorunlu dersler; yüksek lisans programları için lisans programlarından, doktora programları için lisans ve/veya yüksek lisans programlarından da seçilebilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(46, 'Bilimsel hazırlık programında alınması zorunlu dersler adayın kayıtlı olduğu programdaki derslerine yerine geçer mi?', 'Bilimsel hazırlık programında alınması zorunlu dersler, ilgili lisansüstü programını tamamlamak için gerekli görülen derslerin yerine geçmez.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(47, 'Bilimsel hazırlık programındaki bir öğrenci bilimsel hazırlık derslerinin yanı sıra kayıtlı olduğu lisansüstü programdaki derslerden alabilir mi?', 'Bilimsel hazırlık programındaki bir öğrenci, bilimsel hazırlık derslerinin yanı sıra ilgili enstitü anabilim dalı başkanlığının önerisi ve EYK onayı ile lisansüstü programından da dersler alabilir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(48, 'Bilimsel hazırlık programı ve lisansüstü programa yönelik alınacak dersler toplamda kaç AKTS olmalıdır?', 'Bilimsel hazırlık programı ve lisansüstü programa yönelik alınacak derslerin toplamı bir yarıyılda 30 AKTS kredisini geçemez.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(49, 'Bilimsel hazırlık programına kaydolan öğrenci hangi haklara sahiptir?', 'Bilimsel hazırlık programına kaydolan öğrenci lisansüstü öğretimdeki diğer öğrencilerle aynı haklara sahiptir.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(50, 'Bilimsel hazırlık programında alınan dersler transkripte görülüp not ortalamasına dahil edilir mi?', 'Bilimsel hazırlık programında alınan dersler, öğrenim durum belgesinde (transkript) görülür. Ancak, not ortalaması hesaplamalarına katılmaz.', 'GENEL BAŞVURU VE DEĞERLENDİRME'),
(51, 'Bilimsel hazırlıkta geçirilecek süre öğrencinin  lisansüstü program süresinden sayılır mı?', 'Hayır. Lisansüstü program süresinden sayılmaz.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(52, 'Tezli yüksek lisans programında kaç kredi, AKTS ve ders alınması zorunludur?', 'Tezli yüksek lisans programı toplam 21 ulusal ve 120 AKTS kredisinden az olmamak koşuluyla en az 7 (yedi) ders ile seminer dersi ve tez çalışmasından oluşur. Seminer dersi ve tez çalışması kredisiz olup başarılı (B) veya başarısız (K) olarak değerlendirilir.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(53, 'Tezli yüksek lisans programında bir eğitim-öğretim yılında kaç AKTS almak gerekir?', 'Tezli yüksek lisans programında bir eğitim-öğretim yılı 60 AKTS kredisinden az olamaz.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(54, 'Tezli yüksek lisansta lisans düzeyinden dersler alınabilir mi?', 'Öğrencinin alacağı derslerin en çok ikisi, lisans öğrenimi sırasında alınmamış olması kaydıyla, lisans derslerinden seçilebilir.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(55, 'Tezli yüksek lisansta diğer yükseköğretim kurumlarından ders alınabilir mi?', 'Enstitü Ana Bilim Dalı Başkanlığının önerisi ve Enstitü Yönetim Kurulunun onayı ile diğer yükseköğretim kurumlarında verilmekte olan lisansüstü derslerden en fazla 2 (iki) ders alabilir.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(56, 'Tezli yüksek lisans programında danışman ataması ne zaman yapılır?', 'Tezli yüksek lisans programına kayıt yaptıran öğrenciye, Fırat Üniversitesi Lisansüstü Programlarda Akademik Danışmanlık Yönergesi hükümleri uyarınca en geç ilk dönemin sonuna kadar danışman atanır.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(57, 'Tezli yüksek lisans programının süresi kaç yıldır?', 'Tezli yüksek lisans programının süresi, öğrencinin her dönem için kayıt yaptırıp yaptırmadığına bakılmaksızın 4 (dört) yarıyıl olup program en çok 6 (altı) yarıyılda tamamlanır.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(58, 'Tezli yüksek lisans programında dersler ve seminer dersi en geç kaçıncı döneme kadar başarılmalıdır?', '(2) Dört yarıyıl sonunda öğretim planında yer alan kredili derslerini ve seminer dersini başarıyla tamamlayamayan veya bu süre içerisinde başarı koşullarını/ölçütlerini yerine getiremeyen öğrencilerin enstitü ile ilişiği kesilir.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(59, 'Azami süreler içinde tez çalışmasını tamamlamayan veya tez savunmasında başarısız olan öğrenciler ile ilgili süreç nasıl devam eder?', 'Azami süreler içerisinde ise tez çalışmasında ve tez savunmasında başarısız olan veya tez savunmasına girmeyen öğrencinin enstitü ile ilişiği kesilir. Öğrenci azami süresi içerisinde tez savunma sınavına girmek zorundadır.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(60, 'Azami süresi içerisinde tezini teslim etmiş, tez savunmasına girmiş ancak tezinde düzeltme verilmiş öğrencilerin tez düzeltme için verilen sürenin azami süresiyi aşması durumunda süreç nasıl işler?', 'Azami süresi içerisinde tezini teslim etmiş, tez savunmasına girmiş ancak tezinde düzeltme verilmiş öğrencilerin tez düzeltme için verilen sürenin azami süresiyi aşması ve dönem içerisine denk düşmesi halinde bu süre azami sürenin dışında tutulur ve öğrenciye dönem için kayıt hakkı tanınır. Öğrencinin kayıt durumu “aktif bekleyen öğrenci” olarak düzenlenir. Bu durumdaki öğrenci hiçbir derse kayıt yaptıramaz.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(61, 'Yüksek lisans tez önerisi ne zaman verilmelidir?', 'Yüksek lisans tez önerisi, danışmanın gözetiminde öğrenci tarafından hazırlanır ve en erken ikinci yarıyılın başında veya en geç ikinci yarıyılın sonunda danışman tarafından Enstitü Ana Bilim Dalı Başkanlığına/Program Koordinatörlüğüne sunulur. Tez önerisi, ilgili kurulda görüşüldükten sonra gerekli görülmesi halinde düzeltmeler yapılarak enstitüye sunulur. Tez konusu, Enstitü Yönetim Kurulu tarafından tescillenir.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(62, 'Tez önerisinin verilmemesi veya kabul edilmemesi hâlinde AKTS hesaplanır mı?', 'Tez önerisinin verilmemesi veya kabul edilmemesi hâlinde öğrenciye yüksek lisans tezi AKTS kredisi verilmez.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(63, 'Yüksek lisans tez çalışmalarında Etik Kurul ve Araştırma İzin Belgeleri ne zaman alınmalıdır?', 'Tez çalışması, insan ve/veya hayvan üzerinde uygulama yapılarak gerçekleştirilecek çalışmalarda ilgili etik kurullardan Etik Kurul İzin Belgesi, Tez Öneri Formu ile birlikte enstitüye teslim edilir. Anket veya ölçek uygulanan soru-cevap yöntemleri ile gerçekleştirilecek tez çalışmaları için, Bilgilendirilmiş Gönüllü Olur Formu alınmış olsa dahi etik kurul onayı alınması zorunludur. Yasal veya Özel İzin Belgesi gerektiren durumlarda, tez önerisi enstitü tarafından kabul edilen öğrenciler, izin belgelerini aldıktan sonra tez çalışmalarına başlayabilir.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(64, 'Tez konusu değişikliğinde süreç nasıl işler?', 'Tez konusu üzerinde yapılacak değişikliklerde de, tez önerisi ile aynı süreç takip edilir.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(65, 'Yüksek lisans tez savunmasına girebilmek için yayın şartı nelerdir?', 'Öğrencinin, tez savunmasına girebilmesi için alanıyla ilgili ÜAK Doçentlik kriterlerinde tanımlanan şartları sağlayan en az bir ulusal/uluslararası sempozyum/kongrede sözlü bildiri sunması veya ulusal/uluslararası yayınevleri tarafından yayımlanan kitap ile ulusal/uluslararası dergilerde yayımlanmış/yayına kabul edilmiş (DOI numarası almış) makalesinin olması gereklidir. Bu değişiklik 2025-2026 eğitim öğretim döneminden itibaren kayıt yaptıran öğrenciler için geçerli olacaktır.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(66, 'Yüksek lisans tez savunmasına girebilmek için gerekli olan yayın şartı birden fazla kişi için kullanılabilir mi?', 'Yüksek lisans tez savunmasına girebilmek için gerekli olan yayın şartının sağlanması için sunulacak bir akademik faaliyet (makale, bildiri vs.) birden fazla öğrencinin mezuniyeti için kullanılamaz.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(67, 'Yüksek lisans öğrencisi, yüksek lisans tezini Enstitüye teslim ettikten ne kadar sonra tez savunması sınavına girebilir?', 'Yükse lisans öğrencisi, yüksek lisans tezinin jüriye Enstitü tarafından iletildiği tarihten itibaren en geç bir ay içinde tez savunma sınavına girer.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(68, 'Tezi hakkında düzeltme kararı verilen öğrenci  hakkındaki süreç nasıl işler?', 'Tezi hakkında düzeltme kararı verilen öğrenci düzeltmeleri yapılan tezi, en geç üç ay içerisinde ve aynı jüri önünde yeniden savunur.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(69, 'Üç aylık süre sonunda jüri tarafından tezi yetersiz bulunan öğrenci hakkında nasıl bir karar alınır?', 'Üç aylık süre sonunda jüri tarafından tezi yetersiz bulunan öğrenci başarısız bulunur. Tezi kabul edilmeyen veya savunma sınavına girmeyen öğrencinin enstitü ile ilişiği kesilir.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(70, 'Tezi reddedilen öğrenci ile ilgili süreç nasıl ilerler?', 'Tezi reddedilen öğrencinin talepte bulunması hâlinde, tezsiz yüksek lisans programının ders kredi yükü, proje yazımı ve benzeri gereklerini yerine getirmiş olmak kaydıyla kendisine tezsiz yüksek lisans diploması verilir. Tezsiz yüksek lisans programının gereklerini yerine getirememiş öğrencilere koşulları tamamlamaları için bir yarıyıl süre verilir.', 'TEZLİ YÜKSEK LİSANS PROGRAMI'),
(71, 'Tezli yüksek lisansta mezuniyet tarihi nasıl belirlenir?', 'Mezuniyet tarihi, tezin sınav jürisi tarafından imzalanan nüshasının enstitüye teslim edildiği tarihtir.', 'TEZSİZ YÜKSEK LİSANS PROGRAMI'),
(72, 'Tezsiz yüksek lisans programında mezuniyet için toplamda kaç kredi, AKTS ve ders almak gerekir?', 'Tezsiz yüksek lisans programı toplam 30 ulusal krediden ve 60 AKTS kredisinden az olmamak kaydıyla en az 10 ders ve dönem projesi dersinden oluşur. Öğrenci, dönem projesi dersinin alındığı yarıyılda dönem projesi dersine kayıt yaptırmak ve yarıyıl sonunda yazılı proje ve/veya rapor vermek zorundadır.', 'TEZSİZ YÜKSEK LİSANS PROGRAMI'),
(73, 'Tezsiz yüksek lisansta dönem projesinin kredisi var mıdır?', 'Dönem projesi dersi kredisiz olup başarılı veya başarısız olarak değerlendirilir.', 'TEZSİZ YÜKSEK LİSANS PROGRAMI'),
(74, 'Tezsiz yüksek lisans öğrencisine danışman atanır mı?', 'Tezsiz yüksek lisans programına kayıt yaptıran öğrenciye, Fırat Üniversitesi Lisansüstü Programlarda Akademik Danışmanlık Yönergesi hükümleri uyarınca danışman atanır. (4)', 'TEZSİZ YÜKSEK LİSANS PROGRAMI'),
(75, 'Tezsiz yüksek lisansta lisans düzeyinden ders alınabilir mi?', 'Öğrencinin alacağı derslerin en çok üçü, lisans öğrenimi sırasında alınmamış olması kaydıyla, lisans derslerinden seçilebilir.', 'TEZSİZ YÜKSEK LİSANS PROGRAMI'),
(76, 'Tezsiz yüksek lisans programının azami süresi ne kadardır?', 'Tezsiz yüksek lisans programının azami süresi; bilimsel hazırlıkta geçen süre hariç, her dönem için kayıt yaptırıp yaptırmadığına bakılmaksızın en az 2 (iki) yarıyıl, en çok 3 (üç) yarıyıldır.', 'TEZSİZ YÜKSEK LİSANS PROGRAMI'),
(77, 'Tezsiz yüksek lisans programındaki azami süre sonunda mezun olamayan öğrenciler hakkında süreç nasıl ilerler?', 'Azami sürenin sonunda başarısız olan veya programı tamamlayamayan öğrencinin program ile ilişiği kesilir.', 'TEZSİZ YÜKSEK LİSANS PROGRAMI'),
(78, 'Tezsiz yüksek lisansta yeterlik sınavı var mıdır?', 'Tezsiz yüksek lisans programının sonunda yeterlik sınavı uygulanabilir. Bu sınav, enstitü anabilim dalı başkanlığınca kurulan jüri tarafından o dönem mezunlarının hepsi için toplu hâlde yazılı veya sözlü olarak yapılır. Sonuç ilgili enstitüye bildirilir. Sınavda başarısız olan öğrenci, üç ay içerisinde tekrar sınava alınır. Bu sınavda da başarısız olan öğrencinin enstitü ile ilişiği kesilir.', 'TEZSİZ YÜKSEK LİSANS PROGRAMI'),
(79, 'Tezsiz yüksek lisans programında diploma alabilmek için şartlar nelerdir?', 'Kredili derslerini, dönem projesini ve yeterlik sınavını başarıyla tamamlayan öğrencilere tezsiz yüksek lisans diploması verilir. Diploma üzerinde öğrencinin kayıtlı olduğu anabilim dalındaki programın Yükseköğretim Kurulu tarafından onaylanmış adı bulunur.', 'DERS KAYITLARI/DERSLER'),
(80, 'Ders kayıtları ne zaman ve nasıl yapılır?', 'Ders kayıtları Öğrenci İşleri Otomasyon Sistemi (OBS) üzerinden yapılır. Öğrenci, her yarıyılda alacağı dersleri danışmanı ile görüşerek belirler ve akademik takvimde belirtilen süre içinde OBS üzerinden seçerek derse kayıt yapar.', 'DERS KAYITLARI/DERSLER'),
(81, 'Yarıyıl başında seçilen dersler değişebilir mi?', 'Yarıyıl başında seçilen dersler yine akademik takvimde belirtilen tarihler içerisinde danışmanın onayı ile ekle/bırak yapılarak değiştirilebilir. Alınacak dersler danışmanın onayı ile kesinleşir.', 'DERS KAYITLARI/DERSLER'),
(82, 'Her yarıyılda toplam kaç AKTS alınır?', 'Her yarıyılda toplam 30 AKTS kredisinde ders kaydı yapılması esastır.', 'DERS KAYITLARI/DERSLER'),
(83, 'Bir yarıyılda en fazla kaç AKTS alınır?', 'Program yeterliliklerini sağlayamayan veya tekrarlamak zorunda olduğu dersi/dersleri bulunan öğrenciye bir yarıyılda en çok 42 AKTS kredisinde derse kayıt hakkı verilir.', 'DERS KAYITLARI/DERSLER'),
(84, 'Öğrencilerin almaları gereken zorunlu dersleri var mıdır?', 'Öğrenciler, lisansüstü öğrenimleri süresince “bilimsel araştırma yöntemleri ile araştırma ve yayın etiği” konularını içeren bir ders almak zorundadır. Ancak, Sağlık Bilimleri Enstitüsü programlarında zorunlu ortak derslerin tümünü almak zorundadır.', 'DERS KAYITLARI/DERSLER'),
(85, 'Bir öğrenci, bir öğretim üyesinden en fazla kaç ders alabilir?', 'Bir öğrenci, kayıtlı olduğu lisansüstü program süresi içinde bir öğretim üyesinden; seminer, uzmanlık alan dersi, doktora yeterlik, tez ve dönem projesi ile enstitü ortak/zorunlu dersleri hariç kredili derslerin en fazla %50’sini alabilir.', 'DERS KAYITLARI/DERSLER'),
(86, 'Öğrenci derslere kayıt yaptırmadığı dönemler öğrenim süresinden sayılır mı?', 'Öğrencinin derslere kayıt yaptırmadan geçirdiği süre, öğrenim süresinden sayılır.', 'DERS KAYITLARI/DERSLER'),
(87, 'Derslere devam şartı var mıdır?', 'Tüm programlarda teorik derslere en az %70, uygulamalı derslere ise en az %80 devam edilmesi zorunludur.', 'DERS KAYITLARI/DERSLER'),
(88, 'Başarısız olunan bir dersin tekrar alınması hâlinde derse devam şartı aranır mı?', 'Evet, devam şartı aranır.', 'DERS KAYITLARI/DERSLER'),
(89, 'Zorunlu olmayan bir dersten başarısız olunması durumunda o dersin yerine başka bir ders alınabilir mi?', 'Zorunlu olmayan bir dersten başarısız olunması durumunda o dersin yerine başka bir ders alınabilir.', 'SEMİNER DERSİ'),
(90, 'Seminer dersinde danışmanın sorumluluğu var mıdır? Seminer konusu nasıl belirlenir?', 'Seminer dersi, danışman sorumluluğunda yürütülür. Seminer konusu danışman ve öğrencinin ortak kararıyla belirlenir.', 'SEMİNER DERSİ'),
(91, 'Seminer dersinde jüri oluşturulur mu? Seminer dersinden başarılı olarak değerlendirme nasıl yapılır?', 'Seminer çalışması, danışman tarafından anabilim dalı başkanlığına önerilen öğretim üyelerinden oluşan üç kişilik jüri tarafından başarılı veya başarısız olarak değerlendirilir.', 'SEMİNER DERSİ'),
(92, 'Seminer çalışmasında seminer kitapçığı nasıl hazırlanır?', 'Seminer çalışmaları, ilgili enstitü tarafından ilan edilmiş yazım kurallarına uygun şekilde hazırlanır ve PDF formatındaki elektronik kopyası enstitüye iletilmek üzere hazırlanır.', 'SEMİNER DERSİ'),
(93, 'Seminer kitapçığı Enstitüye nasıl ve ne zaman teslim edilir?', 'PDF formatındaki seminer kitapçığı ile birlikte sınav tutanakları EABD Başkanının üst yazısı ekinde en geç 3 (üç) iş günü içinde Üniversitenin elektronik belge yönetim sistemi üzerinden enstitüye iletilir.', 'SEMİNER DERSİ'),
(94, 'Seminer dersinden başarısız olunması durumunda izlenecek yol nedir?', 'Öğrencinin başarısız bulunması halinde, aynı yarıyıl içinde olmak koşuluyla 30 (otuz) gün içerisinde öğrenciye yeni bir sunum hakkı verilir.', 'SEMİNER DERSİ'),
(95, 'Seminer dersinin kredisi var mıdır?', 'Seminer dersinin ulusal kredisi olmayıp 6 AKTS’dir.', 'SEMİNER DERSİ'),
(96, 'Seminer, dönem projesi, uzmanlık alan dersi, yeterlik sınavı ve tez değerlendirmelerinin değerlendirme puanları nasıl verilir?', 'Seminer, dönem projesi, uzmanlık alan dersi, yeterlik sınavı ve tez değerlendirmeleri, Başarılı/Başarısız (B/K) şeklinde yapılır.', 'DOKTORA PROGRAMI'),
(97, 'Tezli yüksek lisans derecesi ile doktoraya kabul edilen öğrencilerin mezuniyet için toplamda kaç kredi, AKTS ve ders almaları gerekir?', 'Tezli yüksek lisans derecesi ile kabul edilmiş öğrenciler için toplam 21 ulusal krediden az olmamak koşuluyla; en az 7 (yedi) ders, seminer, yeterlik sınavı, tez önerisi ve tez çalışması ile her eğitim öğretim döneminde en az 60 AKTS olacak şekilde toplamda en az 240 AKTS kredisinden oluşur.', 'DOKTORA PROGRAMI'),
(98, 'Lisans derecesi ile doktoraya kabul edilen öğrencilerin mezuniyet için toplamda kaç kredi, AKTS ve ders almaları gerekir?', 'Lisans derecesi ile kabul edilmiş öğrenciler için ise en az 42 ulusal kredilik 14 (on dört) ders, seminer, yeterlik sınavı, tez önerisi ve tez çalışması ile her eğitim-öğretim döneminde en az 60 AKTS olacak şekilde toplam en az 300 AKTS kredisinden oluşur.', 'DOKTORA PROGRAMI'),
(99, 'Doktorada diğer yükseköğretim kurumlarından ders alınabilir mi?', 'Doktora programlarında EABD Kurulu/Program yürütme kurulunun önerisi ve EYK onayı ile diğer yükseköğretim kurumlarında verilmekte olan derslerden, yüksek lisans derecesi ile kabul edilmiş öğrenciler en fazla 2 (iki), lisans derecesiyle kabul alan öğrenciler en fazla 4 (dört) ders alabilir.', 'DOKTORA PROGRAMI'),
(100, 'Doktorada lisanstan alınan dersler ders yüküne ve doktora kredisine sayılır mı?', 'Lisans dersleri ders yüküne ve doktora kredisine sayılmaz.', 'DOKTORA PROGRAMI'),
(101, 'Doktorada danışman ataması nasıl yapılır?', 'Doktora programına kayıt yaptıran öğrenciye, Fırat Üniversitesi Lisansüstü Programlarda Akademik Danışmanlık Yönergesi hükümleri uyarınca tez danışmanı atanır.', 'DOKTORA PROGRAMI'),
(102, 'Doktora programının süresi nedir?', 'Doktora programı, bilimsel hazırlıkta geçen süre hariç tezli yüksek lisans derecesi ile kabul edilenler her dönem için kayıt yaptırıp yaptırmadığına bakılmaksızın 8 (sekiz) yarıyıl olup azami tamamlama süresi 12 (on iki) yarıyıl; lisans derecesi ile kabul edilenler için 10 (on) yarıyıl olup azami tamamlama süresi 14 (on dört) yarıyıldır.', 'DOKTORA PROGRAMI'),
(103, 'Doktora programı için gerekli kredili dersleri başarıyla tamamlamanın azami süresi nedir?', 'Doktora programı için gerekli kredili dersleri başarıyla tamamlamanın azami süresi, yüksek lisans derecesi ile kabul edilenler için 4 (dört) yarıyıl, lisans derecesi ile kabul edilenler için 6 (altı) yarıyıldır. Bu süre içinde kredili derslerini başarıyla tamamlayamayan öğrencinin enstitü ile ilişiği kesilir.', 'DOKTORA PROGRAMI'),
(104, 'Doktora yeterlik sınavına ne zaman girilir?', 'Yüksek lisans derecesi ile kabul edilen öğrenci en geç beşinci yarıyılın, lisans derecesi ile kabul edilmiş olan öğrenci en geç yedinci yarıyılın sonuna kadar yeterlik sınavına girmek zorundadır.', 'DOKTORA PROGRAMI'),
(105, 'Yeterlik sınavının içeriği nedir?', 'Alandaki temel konular ve kavramlar ile doktora çalışmasıyla ilgili bilimsel araştırma derinliğine yönelik sorular içeriği oluşturur.', 'DOKTORA PROGRAMI'),
(106, 'Yeterlik sınavına kimler girebilir?', 'Derslerini ve seminerini tamamlayan öğrenciler yeterlik sınavına girebilirler.', 'DOKTORA PROGRAMI'),
(107, 'Doktora Yeterlik Sınavına kaç kez girilebilir?', 'Bir öğrenci bir yılda en fazla iki kez yeterlik sınavına girer. Bu süre içerisinde yeterlik sınavına girmeyen öğrencilerin enstitü ile ilişiği kesilir.', 'DOKTORA PROGRAMI'),
(108, 'Doktora Yeterlik Komitesi  kaç kişiden ve nasıl oluşur?', 'Enstitü anabilim dalı kurulu tarafından önerilen ve enstitü yönetim kurulu tarafından onaylanan 5 (beş) kişiden oluşur. Komite üyeleri üç yılda bir yenilenir, yeterli öğretim üyesi bulunan anabilim dallarında üyelerin en az üçü değiştirilir.', 'DOKTORA PROGRAMI'),
(109, 'Yeterlik Komitesinin görevi nedir?', 'Yeterlik komitesi, danışmanın başvurusu üzerine, yeterlik sınav jüri üyelerini ilgili enstitüye önerir.', 'DOKTORA PROGRAMI'),
(110, 'Doktora Yeterlik sınav jürisi ve sınav tarihi nasıl belirlenir?', 'Sınav jürisi ve sınav tarihi enstitü yönetim kurulu kararı ile belirlenir.', 'DOKTORA PROGRAMI'),
(111, 'Doktora Yeterlik Sınav Jürisi kimlerden oluşur?', 'Yeterlik sınav jürisi en az ikisi Üniversitemiz olmak üzere, danışman dâhil beş öğretim üyesinden oluşur. En az birisi Üniversitemiz dışından olmak üzere iki yedek üye belirlenir. Üniversitemiz dışından gelecek jüri üyelerinin farklı yükseköğretim kurumlarından olmaları gerekmektedir.', 'DOKTORA PROGRAMI'),
(112, 'Doktora yeterlik sınavı ne zaman yapılır?', 'Doktora yeterlik sınavı, güz yarıyılı için kasım ve aralık, bahar yarıyılı için ise nisan ve mayıs aylarında yılda iki dönem olarak yapılır.', 'DOKTORA PROGRAMI'),
(113, 'Doktora Yeterlik Sınavı nasıl yapılır?', 'Yeterlik sınavı yazılı ve sözlü olarak iki bölüm hâlinde yapılır.', 'DOKTORA PROGRAMI'),
(114, 'Doktora Yeterlik Sınavından başarılı olma ölçütü nedir?', 'Yazılı sınavda başarılı olan (50/100 ve üzeri puan alan) öğrenci sözlü sınava alınır. Yazılı sınav süresi en az 90 dakika, sözlü sınav süresi ise en az 60 dakikadır. Öğrencinin yeterlik sınavından başarılı sayılabilmesi için yazılı sınav notunun %65’i ile sözlü sınav notunun %35’inin toplamı en az 65/100 olmalıdır.', 'DOKTORA PROGRAMI'),
(115, 'Doktora Yeterlik Sınav jürisi nasıl karar alır?', 'Sınav jürileri öğrencinin başarılı veya başarısız olduğuna salt çoğunlukla karar verir. Bu karar, enstitü anabilim dalı başkanlığınca yeterlik sınavını izleyen üç gün içinde enstitüye tutanakla bildirilir.', 'DOKTORA PROGRAMI'),
(116, 'Doktora Yeterlik sınavında başarısız olunması halinde tekrar sınav hakkı var mıdır?', 'Yeterlik sınavında başarısız olan öğrenci bir sonraki yarıyılda aynı jüri tarafından tekrar sınava alınır. Bu sınavda da başarısız olan öğrencinin doktora programı ile ilişiği kesilir.', 'DOKTORA PROGRAMI'),
(117, 'Tez İzleme Komitesi ne zaman oluşturulur?', 'Yeterlik sınavında başarılı bulunan öğrenci için anabilim dalı kurulunun önerisi ve enstitü yönetim kurulunun onayı ile bir ay içinde bir tez izleme komitesi oluşturulur', 'DOKTORA PROGRAMI'),
(118, 'Tez İzleme Komitesi kaç kişiden ve nasıl oluşur?', 'Tez izleme komitesi üç öğretim üyesinden oluşur. Komitede tez danışmanı ile enstitü anabilim dalı içinden ve dışından birer üye yer alır. İkinci tez danışmanının atanması durumunda ikinci tez danışmanı dilerse oy hakkı olmaksızın komite toplantılarına katılabilir.', 'DOKTORA PROGRAMI'),
(119, 'Tez İzleme Komitesi üyelerinde değişiklik yapılabilir mi?', 'Tez izleme komitesinin kurulmasından sonraki dönemlerde, danışmanın gerekçeli yazılı isteği üzerine EABD kurulunun önerisi ve EYK onayı ile üyelerde değişiklik yapılabilir.', 'DOKTORA PROGRAMI'),
(120, 'Tez İzleme Komiteleri ne zaman toplanır?', 'Tez önerisi kabul edilen öğrenci için tez izleme komitesi, ocak ve haziran ile temmuz ve aralık ayları arasında birer defa olmak üzere yılda en az iki kez toplanır.', 'DOKTORA PROGRAMI'),
(121, 'Tez İzleme Komitesi toplantılarında süreç nasıl ilerler?', 'Öğrenci, toplantı tarihinden en az bir ay önce komite üyelerine yazılı bir rapor sunar. Bu raporda o ana kadar yapılan çalışmaların özeti ve bir sonraki dönemde yapılacak çalışma planı belirtilir. Öğrencinin tez çalışması, komite tarafından başarılı veya başarısız olarak değerlendirilir.', 'DOKTORA PROGRAMI'),
(122, 'Tez İzleme Komitesi öğrenciyi başarısız bulursa süreç nasıl ilerler?', 'Komite tarafından üst üste iki kez veya aralıklı olarak üç kez başarısız bulunan öğrencinin enstitü ile ilişiği kesilir.', 'DOKTORA PROGRAMI'),
(123, 'Öğrencinin doktora tez savunmasına girebilmesi için kaç Tez İzleme Komite raporu gerekmektedir?', 'Öğrencinin tez savunmasına girebilmesi için en az 3 (üç) olumlu Tez İzleme Komite raporu olmalıdır.', 'DOKTORA PROGRAMI'),
(124, 'Tez İzleme Komitesi raporunun olmaması durumunda süreç nasıl ilerler?', 'Tez izleme komite raporunun olmaması durumunda öğrenci başarısız olarak kabul edilir. Başarısız Tez İzleme Komite raporu döneminde öğrenciye doktora tezi AKTS kredisi verilmez.', 'DOKTORA PROGRAMI'),
(125, 'Doktora tez önerisi ne zaman verilmelidir?', 'Doktora yeterlik sınavını başarı ile tamamlayan öğrenci, en geç altı ay içinde yapacağı araştırmanın amacını, yöntemini ve çalışma planını kapsayan tez önerisini tez izleme komitesi önünde sözlü olarak savunur. Tez önerisinin verilmemesi veya kabul edilmemesi hâlinde öğrenciye doktora tezi AKTS kredisi verilmez.', 'DOKTORA PROGRAMI'),
(126, 'Doktora tez önerisinin mazeretsiz olarak sunulmaması durumunda süreç nasıl ilerler?', 'Tez önerisi savunmasına, geçerli bir mazereti olmaksızın belirtilen sürede girmeyen öğrenci, başarısız sayılarak tez önerisi reddedilir. Bu durum tez izleme komitesi raporu ile enstitüye bildirilir.', 'DOKTORA PROGRAMI'),
(127, 'Tez önerisi reddedilen öğrenci için süreç nasıl ilerler?', 'Tez önerisi reddedilen öğrenci, yeni bir danışman ve/veya tez konusu seçme hakkına sahiptir. Bu durumda yeni bir tez izleme komitesi atanabilir. Programa aynı danışmanla devam etmek isteyen öğrenci 3 (üç) ay içinde, danışman ve tez konusunu değiştiren öğrenci ise altı 6 (altı) ay içinde tekrar tez önerisi savunmasına alınır. Tez önerisi bu savunmada da reddedilen öğrencinin enstitü ile ilişiği kesilir.', 'DOKTORA PROGRAMI'),
(128, 'Doktora tez savunmasına girebilmek için gerekli olan kriterler nelerdir?', 'Öğrencinin; tez savunmasına girebilmesi için en az 3 (üç) olumlu tez izleme komite raporunun olması, en az 240 AKTS kredisi alması ve aşağıdaki şartları yerine getirmesi gereklidir.', 'DOKTORA PROGRAMI'),
(129, 'Yüksek lisans ve doktora tezlerinin sonuçlandırılabilmesi için istenen yayın şartları birden fazla aday için kullanılabilir mi?', 'Mezuniyet için sunulacak bir akademik faaliyet (makale, bildiri, proje vb.) birden fazla öğrencinin mezuniyeti için kullanılamaz.', 'DOKTORA PROGRAMI'),
(130, 'Doktorada mezuniyet için yayın şartları nelerdir?', 'a) Doktora eğitimi süresince, alanıyla ilgili SCI (Science Citation Index), SCI-Exp (Science Citation Index Expanded), SSCI (Social Sciences Citation Index) ve AHCI (Arts and Humanities Citation Index) içinde tanımlanan hakemli bir dergide yayımlanmış/yayına kabul edilmiş en az 1 (bir) adet araştırma/derleme makalesi tez ile birlikte enstitüye teslim edilmelidir. Alternatif olarak E-SCI (Emerging Sources Citation Index) veya SCOPUS içinde tanımlanan hakemli bir dergide yayımlanmış/yayına kabul edilmiş (DOI numarası almış) en az 2 (iki) adet araştırma/derleme makalesinin tez ile birlikte enstitüye teslim edilmesi bu maddenin (a) bendini sağlar. Doktora öğrencisi, bu makalelerde birinci isim veya sorumlu yazar (corresponding author) olmalıdır. Vaka, teknik not, editöre mektup, kısa bildiriler (short communications) ve özet bildiriler (brief communications), mezuniyet şartı olan makale/makaleler kapsamında yer almaz. b) Doktora eğitimi süresince, tez çalışmasından üretilmiş olma koşuluyla ÜAK doçentlik kriterlerinde tanımlanan şartları sağlayan en az bir ulusal/uluslararası sempozyum/kongrede sözlü bildiri sunulması gereklidir. c) Doktora teziyle ilgili Fırat Üniversitesi Öğretim Üyeliğine Yükseltilme ve Atanma Yönergesi\'nde tanımlı kurum dışı fonlara (TÜBİTAK, TÜSEB vb.) proje başvurusu yapılması gereklidir. Doktora öğrencisinin proje önerisinde veya yürütülen projede yer aldığına dair gerekli evraklar enstitüye teslim edilmelidir. d)2025-2026 eğitim öğretim döneminden itibaren kayıt yaptıran öğrenciler için geçerli olacaktır.', 'DOKTORA PROGRAMI'),
(131, 'Doktora tez jürisi kimlerden oluşur?', 'Doktora tez jürisi, üçü öğrencinin tez izleme komitesinde yer alan öğretim üyeleri ve en az ikisi kendi yükseköğretim kurumu dışından olmak üzere danışman dâhil 5 (beş) öğretim üyesinden oluşur. Asıl üyelerin dışında biri ilgili anabilim dalında ve biri kurum dışından olmak üzere iki yedek üye belirlenir. Üniversitemiz dışından gelecek jüri üyeleri farklı yükseköğretim kurumlarından olmalıdır.', 'DOKTORA PROGRAMI'),
(132, 'Doktora tez sınavı ne zaman yapılır?', 'En geç bir ay içerisinde doktora tez sınavı yapılır.', 'AKADEMİK DANIŞMANLIK'),
(133, 'Bir yarıyılda kaç lisansüstü öğrenci kontenjanı talebinde bulunulur?', 'Uluslararası öğrenciler hariç, bir yarıyılda talep edilebilecek yüksek lisans kontenjanı en çok 4 (dört), doktora kontenjanı ise 2 (iki)’dir. Üniversite-sanayi işbirliği, Üniversitenin taraf olduğu protokoller ve yüksek bütçeli dış kaynaklı projeler kapsamında kontenjan talep edenlerde bu şart aranmaz.', 'AKADEMİK DANIŞMANLIK'),
(134, 'Bir öğretim üyesi en fazla lisansüstü öğrenciye danışmanlık yapabilir?', 'Bir öğretim üyesinin, en az 2 (iki) tanesi yabancı uyruklu öğrenci olmak kaydıyla aynı anda 14 (on dört) lisansüstü öğrenci danışmanlığı bulunabilir. Yükseköğretim Kurulu ile yapılan protokoller veya üniversite-sanayi işbirliği kapsamında yürütülen lisansüstü faaliyetler ile yasal veya mücbir sebeplerle EYK kararıyla bu sayı %50’ye kadar artırılabilir.', 'AKADEMİK DANIŞMANLIK'),
(135, 'Bilimsel Hazırlık, Türkçe veya Yabancı Dil Hazırlık Programlarında olan öğrencilere danışman ataması yapılır mı?', 'Lisansüstü öğrenim süresinden sayılmayan Bilimsel Hazırlık, Türkçe veya Yabancı Dil Hazırlık Programlarına kayıt yaptıran öğrencilere danışman ataması yapılmaz. Bu öğrencilere, ilgili programı başarıyla tamamladıktan sonra lisansüstü öğrenime başlamaları hâlinde danışman atanır.', 'AKADEMİK DANIŞMANLIK'),
(136, 'Lisansüstü öğrenci danışmanlığı ne zaman sonlandırılır?', 'Üst üste iki yarıyıl kayıt yaptırmayan öğrencinin danışmanlığı ilgili öğretim üyesinin talebi ve EYK kararıyla sonlandırılır. Bu öğrencilere verilecek danışmanlık hizmetini ilgili anabilim/anasanat dalı başkanı yürütür, ancak bu hizmet karşılığında herhangi bir ücret ödenmez. Öğrenci kayıt yaptırdığında yeniden danışman atanır.', 'AKADEMİK DANIŞMANLIK');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `sss`
--
ALTER TABLE `sss`
  ADD PRIMARY KEY (`id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `sss`
--
ALTER TABLE `sss`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=137;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
